# Generated by Django 5.0.7 on 2024-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('describe', models.TextField(blank=True, null=True)),
                ('teacher', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('st_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
