# Generated by Django 5.0.7 on 2024-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ourstudentssay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstudentssay',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
